### ISSUE TITLE
Can support typescript? 

### ISSUE THREAD

**Issue by bdwenxi** [yesmeck/mini-store#6]
Can support typescript?~

**Comment by yesmeck** [comment]
3.0

**Comment by kaysonwu** [comment]
@yesmeck  `3.x` has no declaration file. What should I do?

**Comment by yesmeck** [comment]
@kaysonwu PRs are welcome

**Comment by kaysonwu** [comment]
准备，PR 但是遇到了一个问题，我更改了 build 命令

```json
tsc --declaration
```

然后，编译的时候会报告下面的错误，我看没有编写错误，很好奇

![QQ截图20200724115453](https://user-images.githubusercontent.com/14865584/88359246-8650e300-cda4-11ea-8b29-638d013737d3.png)

**Comment by yesmeck** [comment]
connect 返回类型需要完善下

**Comment by kaysonwu** [comment]
知道了，我将 wrapWithConnect 返回类型，显示定义 `any` 就可以了。看来确实要完善下
