### ISSUE TITLE
please upgrade 'hoist-non-react-statics'

### ISSUE THREAD

**Issue by xiaofengz** [yesmeck/mini-store#8]
i found u upgrade 'hoist-non-react-statics' in your code , but have not npm publish;
npm package now version 3.0.1 still "hoist-non-react-statics": "^2.3.1";
it makes some problem in my project

**Comment by xiaofengz** [comment]
发现问题的经过如下：

![image](https://user-images.githubusercontent.com/25739935/79094098-f6ed6a00-7d88-11ea-9862-7812d325c364.png)
项目启动的时候报错了，根据提示找到由于react-redux引用了‘hoist-non-react-statics’这个包，虽然react-redux的package.json中引用的是3.3.0版本的，但是不知道为什么最终没有用@types/目录下的3.3的‘hoist-non-react-statics’，而引用了node_module/目录最外层的2.3.1版本的‘hoist-non-react-statics’，因为2.3.1版本的‘hoist-non-react-statics’包的index.d.ts文件没有‘NonReactStatics’，所有最终报错了

**Comment by yesmeck** [comment]
3.0.2

**Comment by yesmeck** [comment]
重新发布了，更新下依赖。
